// <auto-generated />
using System;
using ApiDocAssistant.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ApiDocAssistant.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260715182119_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ApiDocAssistant.Domain.Entities.ApiEndpoint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ApiProjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Summary")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ApiProjectId");

                    b.ToTable("ApiEndpoints");
                });

            modelBuilder.Entity("ApiDocAssistant.Domain.Entities.ApiProject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SpecFormat")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ApiProjects");
                });

            modelBuilder.Entity("ApiDocAssistant.Domain.Entities.EndpointParameter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ApiEndpointId")
                        .HasColumnType("uuid");

                    b.Property<string>("In")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Required")
                        .HasColumnType("boolean");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ApiEndpointId");

                    b.ToTable("EndpointParameters");
                });

            modelBuilder.Entity("ApiDocAssistant.Domain.Entities.ApiEndpoint", b =>
                {
                    b.HasOne("ApiDocAssistant.Domain.Entities.ApiProject", "ApiProject")
                        .WithMany("Endpoints")
                        .HasForeignKey("ApiProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApiProject");
                });

            modelBuilder.Entity("ApiDocAssistant.Domain.Entities.EndpointParameter", b =>
                {
                    b.HasOne("ApiDocAssistant.Domain.Entities.ApiEndpoint", "ApiEndpoint")
                        .WithMany("Parameters")
                        .HasForeignKey("ApiEndpointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApiEndpoint");
                });

            modelBuilder.Entity("ApiDocAssistant.Domain.Entities.ApiEndpoint", b =>
                {
                    b.Navigation("Parameters");
                });

            modelBuilder.Entity("ApiDocAssistant.Domain.Entities.ApiProject", b =>
                {
                    b.Navigation("Endpoints");
                });
#pragma warning restore 612, 618
        }
    }
}
